# Generated by Django 5.1.6 on 2025-05-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_companyprofile_description_influencerprofile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='category',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='companies', to='profiles.category'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='influencers', to='profiles.category'),
        ),
    ]
