# Generated by Django 5.1.6 on 2025-05-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_category_remove_companyprofile_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerprofile',
            name='platforms',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
