# Generated by Django 5.1.6 on 2025-05-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_companyprofile_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='x_url',
            field=models.URLField(blank=True, null=True, verbose_name='X (Twitter) URL'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube URL'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='x_url',
            field=models.URLField(blank=True, null=True, verbose_name='X (Twitter) URL'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube URL'),
        ),
    ]
