# Generated by Django 5.1.6 on 2025-05-13 02:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaign_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Niche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='image',
        ),
        migrations.AddField(
            model_name='campaign',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='niches',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='campaigns.niche'),
        ),
    ]
