# Generated by Django 5.1.6 on 2025-05-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_niche_remove_campaign_comments_remove_campaign_image_and_more'),
        ('profiles', '0004_category_remove_companyprofile_industry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='niches',
        ),
        migrations.AddField(
            model_name='campaign',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='profiles.category'),
        ),
        migrations.DeleteModel(
            name='Niche',
        ),
    ]
